#!/bin/bash
# This hook is sourced after a new virtualenv is activated.

function setuptools {
    if python -V 2>&1 | grep -q 'Python 2'; then
        echo 'setuptools<=44'
    else
        echo 'setuptools'
    fi
}

pip install --upgrade pip $(setuptools) wheel pdbpp ipython neovim ropevim black isort
